version: '3.3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: dazai
      POSTGRES_PASSWORD: dazai
      POSTGRES_DB: test_db
    ports:
      - "5444:5432"
    volumes:
      - ./volumes/postgres-data:/var/lib/postgresql
